version: 2.1

executors:
  # Can set image tag in job / workflow
  python:
    parameters:
      image_tag:
        type: string
        default: "3.7"
    docker:
      - image: circleci/python:<< parameters.image_tag >>

commands:
  unpackage-featuretools:
    description: "create featuretools source distribution and unpack it"
    steps:
      - run: |
          python setup.py sdist
          FT_VERSION=$(python setup.py --version)
          tar -zxvf "dist/featuretools-${FT_VERSION}.tar.gz"
          mv "featuretools-${FT_VERSION}" unpacked_sdist
          echo $(ls)
  install-featuretools:
    description: "install featuretools from source distribution"
    steps:
      - run : |
          source venv/bin/activate
          pip install -e unpacked_sdist/
          pip install -r unpacked_sdist/test-requirements.txt
  run-packaged-tests:
    description: "run unit tests on packaged testing files"
    steps:
      - run: |
          source venv/bin/activate
          cd unpacked_sdist
          pytest
  install-ft-complete:
    description: "install featuretools[complete]"
    steps:
      - run: |
          virtualenv venv
          source venv/bin/activate
          pip install -e unpacked_sdist/[complete]
  run-import-tests:
    description: "testing imports of add-ons"
    steps:
      - run: |
          source venv/bin/activate
          python -c "import featuretools_tsfresh_primitives"
          python -c "import featuretools_update_checker"
  lint:
    description: "run linter test"
    steps:
      - run: source venv/bin/activate && make lint

jobs:
  package_featuretools:
    working_directory: ~/featuretools
    parameters:
      image_tag:
        type: string
        default: "3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - checkout
      - unpackage-featuretools
      - persist_to_workspace:
          root: ~/featuretools
          paths:
            - unpacked_sdist

  install_ft:
    working_directory: ~/featuretools
    parameters:
      image_tag:
        type: string
        default: "3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - run: virtualenv venv
      - install-featuretools
      - persist_to_workspace:
          root: ~/featuretools
          paths:
            - venv

  unit_tests:
    working_directory: ~/featuretools
    parameters:
      image_tag:
        type: string
        default: "3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - run: sudo apt update && sudo apt install -y graphviz
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - run-packaged-tests

  lint_test:
    working_directory: ~/featuretools
    parameters:
      image_tag:
        type: string
        default: "3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - lint

  build_docs:
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo apt update && sudo apt install -y pandoc
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - run: |
          source venv/bin/activate
          make -C docs/ -e "SPHINXOPTS=-W" clean html

  install_ft_complete:
    working_directory: ~/featuretools
    parameters:
      image_tag:
        type: string
        default: "3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - install-ft-complete
      - run-import-tests

  changelog_updated:
    working_directory: ~/featuretools
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run: cat docs/source/changelog.rst | grep ":pr:\`${CIRCLE_PULL_REQUEST##https://github.com/Featuretools/featuretools/pull/}\`"

  install_dev_reqs:
    working_directory: ~/featuretools
    parameters:
      image_tag:
        type: string
        default: "3.7"
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - attach_workspace:
          at: ~/featuretools
      - run: |
          source venv/bin/activate
          pip install -r unpacked_sdist/dev-requirements.txt
      - persist_to_workspace:
          root: ~/featuretools
          paths:
            - venv

workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - package_featuretools:
          name: "py27 package featuretools"
          image_tag: "2.7"
      - package_featuretools:
          name: "py35 package featuretools"
          image_tag: "3.5"
      - package_featuretools:
          name: "py36 package featuretools"
          image_tag: "3.6"
      - package_featuretools:
          name: "py37 package featuretools"
      - install_ft:
          name: "py27 install featuretools"
          image_tag: "2.7"
          requires:
            - "py27 package featuretools"
      - install_ft:
          name: "py35 install featuretools"
          image_tag: "3.5"
          requires:
            - "py35 package featuretools"
      - install_ft:
          name: "py36 install featuretools"
          image_tag: "3.6"
          requires:
            - "py36 package featuretools"
      - install_ft:
          name: "py37 install featuretools"
          requires:
            - "py37 package featuretools"
      - unit_tests:
          name: "py27 unit tests"
          image_tag: "2.7"
          requires:
            - "py27 install featuretools"
      - unit_tests:
          name: "py35 unit tests"
          image_tag: "3.5"
          requires:
            - "py35 install featuretools"
      - unit_tests:
          name: "py36 unit tests"
          image_tag: "3.6"
          requires:
            - "py36 install featuretools"
      - unit_tests:
          name: "py37 unit tests"
          requires:
            - "py37 install featuretools"
      - install_dev_reqs:
          name: "py27 install dev reqs"
          image_tag: "2.7"
          requires:
            - "py27 install featuretools"
      - install_dev_reqs:
          name: "py35 install dev reqs"
          image_tag: "3.5"
          requires:
            - "py35 install featuretools"
      - install_dev_reqs:
          name: "py36 install dev reqs"
          image_tag: "3.6"
          requires:
            - "py36 install featuretools"
      - install_dev_reqs:
          name: "py37 install dev reqs"
          requires:
            - "py37 install featuretools"
      - lint_test:
          name: "py27 lint test"
          image_tag: "2.7"
          requires:
            - "py27 install dev reqs"
      - lint_test:
          name: "py35 lint test"
          image_tag: "3.5"
          requires:
            - "py35 install dev reqs"
      - lint_test:
          name: "py36 lint test"
          image_tag: "3.6"
          requires:
            - "py36 install dev reqs"
      - lint_test:
          name: "py37 lint test"
          requires:
            - "py37 install dev reqs"
      - build_docs:
          name: "build docs"
          requires:
            - "py37 install dev reqs"
      - install_ft_complete:
          name: "py27 install featuretools complete test"
          image_tag: "2.7"
          requires:
            - "py27 package featuretools"
      - install_ft_complete:
          name: "py35 install featuretools complete test"
          image_tag: "3.5"
          requires:
            - "py35 package featuretools"
      - install_ft_complete:
          name: "py36 install featuretools complete test"
          image_tag: "3.6"
          requires:
            - "py36 package featuretools"
      - install_ft_complete:
          name: "py37 install featuretools complete test"
          requires:
            - "py37 package featuretools"
      - changelog_updated:
          name: "changelog updated"
          filters:
            branches:
              ignore: /^master?/
