version: 2.1

commands:
  unpackage-featuretools:
    description: "create featuretools source distribution and unpack it"
    steps:
      - run: |
          python setup.py sdist
          FT_VERSION=$(python setup.py --version)
          tar -zxvf "dist/featuretools-${FT_VERSION}.tar.gz"
          mv "featuretools-${FT_VERSION}" unpacked_dist
          echo $(ls)
  install-featuretools:
    description: "install featuretools from source distribution"
    steps:
      - run : |
          source venv/bin/activate
          pip install -e unpacked_dist/
          pip install -r unpacked_dist/test-requirements.txt
  run-packaged-tests:
    description: "run unit tests on packaged testing files"
    steps:
      - run: |
          source venv/bin/activate
          cd unpacked_dist
          pytest
  install-ft-complete:
    description: "install featuretools[complete]"
    steps:
      - run: |
          virtualenv venv
          source venv/bin/activate
          pip install -e unpacked_dist/[complete]
  run-import-tests:
    description: "testing imports of add-ons"
    steps:
      - run: |
          source venv/bin/activate
          python -c "import featuretools_tsfresh_primitives"
          python -c "import featuretools_update_checker"
  lint:
    description: "run linter test"
    steps:
      - run: |
          source venv/bin/activate
          pip install -r unpacked_dist/dev-requirements.txt
      - run: source venv/bin/activate && make lint

jobs:
  "Package Featuretools":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - unpackage-featuretools
      - persist_to_workspace:
          root: ~/featuretools
          paths:
            - unpacked_sdist

  "Install Featuretools":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - run: virtualenv venv
      - install-featuretools
      - persist_to_workspace:
          root: ~/featuretools
          paths:
            - venv

  "Run Unit Tests":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - run: sudo apt update && sudo apt install -y graphviz pandoc
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - run-packaged-tests

  "Run Linter":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - lint

  "Build Docs":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - run: |
          source venv/bin/activate
          make -C docs/ -e "SPHINXOPTS=-W" clean html

  "Install featuretools extras":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: ~/featuretools
      - install-ft-complete
      - run-import-tests

  "Changelog Updated":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: cat docs/source/changelog.rst | grep ":pr:\`${CIRCLE_PULL_REQUEST##https://github.com/Featuretools/featuretools/pull/}\`"

workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - "Package Featuretools"
      - "Install Featuretools":
          requires:
            - "Package Featuretools"
      - "Run Unit Tests":
          requires:
            - "Install Featuretools"
      - "Run Linter":
          requires:
            - "Install Featuretools"
      - "Build Docs":
          requires:
            - "Install Featuretools"
      - "Install featuretools extras":
          requires:
            - "Package Featuretools"
      - "Changelog Updated":
          filters:
            branches:
              ignore: /^master?/
